import turtle as t

t.speed(7)
t.penup()
t.goto(-100, 0)


t.write('Запад', align='right')
t.forward(20)
t.pendown()
t.forward(100)
t.left(90)
t.forward(100)
t.penup()
t.forward(20)
t.write('Север', align='center')
t.backward(20)
t.pendown()
t.backward(200)
t.penup()
t.backward(20)
t.write('Юг', align='center')
t.forward(20)
t.pendown()
t.forward(100)
t.right(90)
t.forward(100)
t.penup()
t.forward(20)
t.write('Восток', align='left')
t.backward(20)
t.pendown()
t.backward(100)
t.right(90)
t.forward(30)
t.left(90)
t.circle(30)